language: android
jdk: oraclejdk7
sudo: false

android:
  components:
    # Use the latest revision of Android SDK Tools
    - platform-tools
    - tools
    # The BuildTools version used by this project
    - build-tools-22.0.1
    # The SDK version used to compile this project
    - android-22
    # Additional components	
    - extra-android-support
    - extra-android-m2repository
    # Emulators for tests
    # - sys-img-armeabi-v7a-android-19
    # - sys-img-armeabi-v7a-android-21
    # - sys-img-x86-android-17
  licenses:
    - 'android-sdk-license-.+'

env:
  global:
    # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
    - ANDROID_SDK_VERSION="r24.3.3"

before_script:
  - chmod +x gradlew
  # - android-wait-for-emulator
  - wget http://dl.google.com/android/android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - tar -zxf android-sdk_${ANDROID_SDK_VERSION}-linux.tgz
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  
install: /bin/true

script:
  - ./gradlew build